### ISSUE TITLE
Fail to sync any files | couldn't validate schema[Bug]

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [Bartek532/rssmarkable#82]
**To Reproduce**
Steps to reproduce the behavior: Sync any feeds.
![image](https://github.com/Bartek532/rssmarkable/assets/13170204/46e598b1-385c-4f0c-9235-3733a2ce8df0)

**Actual behavior**
```
couldn't validate schema: [{"id":"One of my remarkable file ID"","hash":"Same file hash"","type":"DocumentType","visibleName":"File name","lastModified":"epoch time of that file","fileType":"epub","pinned":false,"lastOpened":"0"},{"id":"An another file of my remarkable ID"[...]
    at le (/app/node_modules/.pnpm/rmapi-js@3.1.0/node_modules/rmapi-js/bundle/rmapi-js.cjs.min.js:9:10170)
    at et.getEntriesMetadata (/app/node_modules/.pnpm/rmapi-js@3.1.0/node_modules/rmapi-js/bundle/rmapi-js.cjs.min.js:12:3703)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RemarkableStrategy.getFolder (/app/apps/sync/dist/device/remarkable/remarkable.strategy.js:65:23)
    at async FeedQueueService.upsertFeedFolder (/app/apps/sync/dist/queue/feed/feed.service.js:45:24)
    at async FeedQueueService.syncArticle (/app/apps/sync/dist/queue/feed/feed.service.js:63:26)
    at async FeedQueueConsumer.syncFeed (/app/apps/sync/dist/queue/feed/feed.consumer.js:58:13)
```
Seems to report the same error regardless if an RSS folder was created at the root of the remarkable or not.

**Expected behavior**
Be able to sync correctly and send all the generated EPUB files

**Notes**
I don't wish to share the full error message in a log file, for privacy reasons.

**Comment by Bartek532** [comment]
Thanks for reporting, will take a look on it!
